document.write('<header>');
document.write('<ul class="menu">');
document.write('	<li class="noclick">Dr. DANce</li>');
document.write('	<li onclick="window.open(\'index.html\');">How can we exercise?</li>');
document.write('	<li onclick="window.open(\'why.html\');">Why should we exercise?</li>');
document.write('	<li onclick="window.open(\'how-much.html\');">How much should we exercise?</li>');
document.write('	<!-- <li style="float:right;" onclick="window.open(\'https://github.com/dkats/DrDANce\');">Source code</li> -->');
document.write('	<!-- <li style="float:right;" onclick="window.open(\'mailto:djk175@case.edu?subject=Dr. DANce bug! Ew!\');">Report bug</li> -->');
document.write('	<!-- <li style="float:right;" onclick="window.open(\'mailto:djk175@case.edu?subject=Dr. DANce question\');">Contact</li> -->');
document.write('	<li style="float:right;" onclick="window.open(\'references.html\');">References</li>');
document.write('	<li style="float:right;" onclick="window.open(\'about.html\');">About</li>');
document.write('</ul>');
document.write('</header>');