document.write('<header>');
document.write('<ul class="menu">');
document.write('	<li class="noclick" style="padding:3px; padding-left:0px"><img src="files/Logo.png" height="36pt"></img></li>');
document.write('	<li onclick="window.open(\'index.html\',\'_self\');" id="header_howcan">How can we exercise?</li>');
document.write('	<li onclick="window.open(\'why.html\',\'_self\');" id="header_why">Why should we exercise?</li>');
document.write('	<li onclick="window.open(\'how-much.html\',\'_self\');" id="header_howmuch">How much should we exercise?</li>');
document.write('	<li style="float:right;" onclick="window.open(\'references.html\',\'_self\');" id="header_ref">References</li>');
document.write('	<li class="dropdown" style="float:right;padding:0;">');
document.write('		<div class="dropmain" onclick="window.open(\'about.html\',\'_self\');" id="header_about">About</div>');
document.write('		<div class="droprest" onclick="window.open(\'about-physicians.html\',\'_self\');" id="header_aboutphys">For physicians</div');
document.write('	</li>');
document.write('</ul>');
document.write('</header>');